### ISSUE TITLE
Why bem not ym?

### ISSUE THREAD

**Issue by belozer** [bem/babel-plugin-bem#11]
Why `bem`, not `ym`? Like import from modular system `ymodules`...

**Example:**
`common.blocks/user/_admin/user_admin.js`

```js

/**
 * @module user <- Module name for modules.define
 *                 The solution for loader_type_js and user_admin cases
 */
import { declMod } from 'ym:user';
import Button from 'ym:button';
import loaderJs from 'ym:loader_type_js';

export default declMod(....)
```
`common.blocks/loader/_type/loader_type_js.js`
```js

/**
 * @module loader_type_js
 */
export default (url) => { ... };
```
@zxqfox @veged

**Comment by belozer** [comment]
Or is this plugin out of date? In favor of https://github.com/bem/babel-plugin-bem-import in bem-core/bem-components

**Comment by veged** [comment]
kind of... https://github.com/bem/babel-plugin-bem-import provide better approach
