### ISSUE TITLE
Update to Babel 6

### ISSUE THREAD

**Issue by narqo** [bem/babel-plugin-bem#7]
Because science, of course!

See babel plugin handbook for references: https://github.com/thejameskyle/babel-plugin-handbook

**Comment by Lehakos** [comment]
Проект заглох? А жаль, так хотелось бы чтобы работало на Babel 6

**Comment by narqo** [comment]
Мы решили пересмотреть концепцию: https://github.com/bem/webpack-bem-loader 
В качестве референсного потребителя, можно смотреть https://github.com/bem/bem-react-core
